parameters:
  - name: servicePath
    type: string
jobs:
  - job: DeployService
    steps:
      - checkout: self
      - script: |
          cd ${{ parameters.servicePath }}
          echo "Deploying ${{ parameters.servicePath }}"