name: Build and Push Docker Image

on:
  push:
    branches:
      - none
    paths:
      - 'app/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: guardnew.azurecr.io
          username: ${{ secrets.ARM_CLIENT_ID }}
          password: ${{ secrets.ARM_CLIENT_SECRET }}

      - name: Build and Push frontend
        run: |
          docker build -t guardnew.azurecr.io/frontend:latest ./app/frontend
          docker push guardnew.azurecr.io/frontend:latest

      - name: Build and Push backend
        run: |
          docker build -t guardnew.azurecr.io/backend:latest ./app/backend
          docker push guardnew.azurecr.io/backend:latest
